# Generated by Django 5.1.1 on 2024-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=40)),
                ('car_model', models.CharField(max_length=40)),
                ('car_year', models.IntegerField()),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
